# 1. Estágio base para execução da aplicação
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080

# 2. Estágio de build utilizando o SDK completo
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["GestaoFinanceira.Api.csproj", "."]
RUN dotnet restore "./GestaoFinanceira.Api.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "GestaoFinanceira.Api.csproj" -c Release -o /app/build

# 3. Estágio de publicação
FROM build AS publish
RUN dotnet publish "GestaoFinanceira.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

# 4. Estágio final
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "GestaoFinanceira.Api.dll"]